  
% find abf files
currdir = pwd;
% Set the path to your data here
pathname = '';
% pathname = uigetdir;
cd(pathname)
files1 = dir('*.mat');
cd(currdir)
files = cell(length(files1),1);
for i = 1:length(files)
    files{i} = files1(i).name;
end

clear files1

%%

if exist('fig','var') && ishandle(fig)
    fig = gcf;
    delete(get(fig,'children'));
else 
    sz = get(0,'screensize');
    fig = figure('Name',['Excitation Inhibition Balance'],'NumberTitle','off','toolbar','figure','position',[1 0.14*sz(4) sz(3) 0.7*sz(4)],'doublebuffer','on');
end


%%

dpfiles = uicontrol('Style','popupmenu','Units','normalized','String',files,...
    'Position',[.85 .9 .11 .025],'FontSize',9,...
    'BackgroundColor',[1 1 1],...
    'callback','st1 = get(dpfiles,''value'');clear(''expr'',''inex'');load([pathname files{st1}]);sweepplot;');

st1 = get(dpfiles,'value');
load([pathname files{st1}]);



%% Checkboxes

bsvm = uicontrol('Style','checkbox','Units','normalized',...
    'Position',[.85 .85 .01 .03],'BackgroundColor',[.8 .8 .8],'value',1,...
    'callback','gui.sweepplot');
uicontrol('Style','text','Units','normalized',...
    'String','Recorded traces',...
    'HorizontalAlignment','left',...
    'Position',[.86 .845 .05 .03],'FontSize',9,...
    'BackgroundColor',[.8 .8 .8]);

bsrec = uicontrol('Style','checkbox','Units','normalized',...
    'Position',[.85 .82 .01 .03],'BackgroundColor',[.8 .8 .8],'value',0,...
    'callback','gui.sweepplot');
uicontrol('Style','text','Units','normalized',...
    'String','Reconstructes traces',...
    'HorizontalAlignment','left',...
    'Position',[.86 .815 .064 .03],'FontSize',9,...
    'BackgroundColor',[.8 .8 .8]);

bsstim = uicontrol('Style','checkbox','Units','normalized',...
    'Position',[.85 .79 .01 .03],'BackgroundColor',[.8 .8 .8],'value',0,...
    'callback','gui.sweepplot');
uicontrol('Style','text','Units','normalized',...
    'String','Stimulation',...
    'HorizontalAlignment','left',...
    'Position',[.86 .785 .064 .03],'FontSize',9,...
    'BackgroundColor',[.8 .8 .8]);

bsge = uicontrol('Style','checkbox','Units','normalized',...
    'Position',[.85 .76 .01 .03],'BackgroundColor',[.8 .8 .8],'value',0,...
    'callback','gui.sweepplot');
uicontrol('Style','text','Units','normalized',...
    'String','Excitation',...
    'HorizontalAlignment','left',...
    'Position',[.86 .755 .064 .03],'FontSize',9,...
    'BackgroundColor',[.8 .8 .8]);

bsgi = uicontrol('Style','checkbox','Units','normalized',...
    'Position',[.85 .73 .01 .03],'BackgroundColor',[.8 .8 .8],'value',0,...
    'callback','gui.sweepplot');
uicontrol('Style','text','Units','normalized',...
    'String','Inhibition',...
    'HorizontalAlignment','left',...
    'Position',[.86 .725 .064 .03],'FontSize',9,...
    'BackgroundColor',[.8 .8 .8]);

bsbsln = uicontrol('Style','checkbox','Units','normalized',...
    'Position',[.85 .70 .01 .03],'BackgroundColor',[.8 .8 .8],'value',0,...
    'callback','gui.sweepplot');
uicontrol('Style','text','Units','normalized',...
    'String','Baseline',...
    'HorizontalAlignment','left',...
    'Position',[.86 .695 .064 .03],'FontSize',9,...
    'BackgroundColor',[.8 .8 .8]);

bssat = uicontrol('Style','checkbox','Units','normalized',...
    'Position',[.85 .67 .01 .03],'BackgroundColor',[.8 .8 .8],'value',0,...
    'callback','gui.sweepplot');
uicontrol('Style','text','Units','normalized',...
    'String','Saturation',...
    'HorizontalAlignment','left',...
    'Position',[.86 .665 .064 .03],'FontSize',9,...
    'BackgroundColor',[.8 .8 .8]);

%% buttons
figbtn = uicontrol('style','pushbutton','String','Figure out','Units','normalized',...
    'Position',[.85 .4 .03 .03],'BackgroundColor',[.8 .8 .8],...
    'callback','gui.figit');

expbtn = uicontrol('style','pushbutton','String','Expression','Units','normalized',...
    'Position',[.89 .4 .03 .03],'BackgroundColor',[.8 .8 .8],...
    'callback','gui.showexpr');

itbtn = uicontrol('style','pushbutton','String','Iteration','Units','normalized',...
    'Position',[.93 .4 .03 .03],'BackgroundColor',[.8 .8 .8],...
    'callback','gui.showit');

postbtn = uicontrol('style','pushbutton','String','More','Units','normalized',...
    'Position',[.97 .4 .03 .03],'BackgroundColor',[.8 .8 .8],...
    'callback','gui.inexposthoc');

%%

trax = subplot('position',[0.03 0.06 0.8 0.93]);
set(gca,'xlim',[time(1) time(end)])
set(gca,'ylim',[-100 10])
box on

cond = subplot('position',[0.86 0.06 0.13 0.3]);
% set(gca,'xlim',[time(1) time(end)])
% set(gca,'ylim',[-.1 .01])
box on

gui.sweepplot








